export enum CulturalDiet {
  MEDITERRANEAN = 'mediterranean',
  ASIAN = 'asian',
  AFRICAN = 'african',
  MIDDLE_EASTERN = 'middle_eastern',
  LATIN_AMERICAN = 'latin_american',
  INDIAN = 'indian',
  EUROPEAN = 'european',
  AMERICAN = 'american',
  VEGETARIAN = 'vegetarian',
  VEGAN = 'vegan',
  PESCATARIAN = 'pescatarian',
  KETO = 'keto',
  PALEO = 'paleo',
  GLUTEN_FREE = 'gluten_free',
  DAIRY_FREE = 'dairy_free',
  LOW_CARB = 'low_carb',
  LOW_FAT = 'low_fat',
  RAW_FOOD = 'raw_food',
  INTERMITTENT_FASTING = 'intermittent_fasting',
  HALAL = 'halal',
  KOSHER = 'kosher',
  ORGANIC = 'organic',
  WHOLE30 = 'whole30',
  DASH = 'dash',
  FLEXITARIAN = 'flexitarian',
  NO_PREFERENCE = 'no_preference'
}